name: weather_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.2
  json_annotation: ^4.8.1
  intl: ^0.18.1
  flutter_native_splash: ^2.2.4
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  shimmer: ^3.0.0
  get_it: ^7.6.7

  weather: ^3.1.1

  location: ^5.0.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.8
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    

    - assets/images/
    - assets/fonts/
    - assets/icons/


